=== MakaylaSoh/csc-366-xml-proj/src/dtd/supplier.dtd
<!-- Address -->
<!ELEMENT country (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT address (country, state, city, street, zip)>

<!-- Supplier Contract -->
<!ELEMENT start_date (#PCDATA)>
<!ELEMENT end_date (#PCDATA)>
<!ELEMENT details (#PCDATA)>
<!ELEMENT contract (start_date, end_date, details)>

<!-- Supplier -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT supplier (name, address, contract)>

=== MakaylaSoh/csc-366-xml-proj/src/supplier_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE supplier_elements SYSTEM "dtd/supplier.dtd">

<supplier>
  <name>Cinnabon</name>
  <address>
    <country>country1</country>
    <state>state2</state>
    <city>city2</city>
    <street>street2</street>
    <zip>22222</zip>
  </address>
  <contract>
    <start_date>2022-06-15</start_date>
    <end_date>2024-06-14</end_date>
    <details>Negotiation on seasonal items.</details>
  </contract>
</supplier>
